spring:
  datasource:
    url: jdbc:h2:mem:bookdb;MODE=PostgreSQL

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  main:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none
        jdbc:
          batch_size: 10
          generate_statistics: true